In [19]:
import pandas as pd
df=pd.read_csv("train.csv")

In [20]:
df=df.dropna()

In [22]:
df


duration protocol_type   service  flag  src_bytes  dst_bytes  land  \
0             0           tcp  ftp_data    SF        491          0     0   
1             0           udp     other    SF        146          0     0   
2             0           tcp   private    S0          0          0     0   
3             0           tcp      http    SF        232       8153     0   
4             0           tcp      http    SF        199        420     0   
...         ...           ...       ...   ...        ...        ...   ...   
20326         0           tcp   private   REJ          0          0     0   
20327         0           tcp   private    S0          0          0     0   
20328         0           tcp      http    SF        332        767     0   
20329         0           tcp     pop_3  RSTO          0          0     0   
20330         0           tcp      http    SF        211       2570     0   

       wrong_fragment  urgent  hot  ...  dst_host_srv_count  \
0                   0       0    0  ...                25.0   
1                   0       0    0  ...                 1.0   
2                   0       0    0  ...                26.0   
3                   0       0    0  ...               255.0   
4                   0       0    0  ...               255.0   
...               ...     ...  ...  ...                 ...   
20326               0       0    0  ...                 2.0   
20327               0       0    0  ...                 7.0   
20328               0       0    0  ...               255.0   
20329               0       0    0  ...                12.0   
20330               0       0    0  ...               255.0   

       dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                        0.17                    0.03   
1                        0.00                    0.60   
2                        0.10                    0.05   
3                        1.00                    0.00   
4                        1.00                    0.00   
...                       ...                     ...   
20326                    0.07                    0.14   
20327                    0.03                    0.05   
20328                    1.00                    0.00   
20329                    0.05                    0.07   
20330                    1.00                    0.00   

       dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                             0.17                         0.00   
1                             0.88                         0.00   
2                             0.00                         0.00   
3                             0.03                         0.04   
4                             0.00                         0.00   
...                            ...                          ...   
20326                         0.04                         0.00   
20327                         0.00                         0.00   
20328                         0.00                         0.00   
20329                         0.00                         0.00   
20330                         0.01                         0.03   

       dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                      0.00                      0.00                  0.05   
1                      0.00                      0.00                  0.00   
2                      1.00                      1.00                  0.00   
3                      0.03                      0.01                  0.00   
4                      0.00                      0.00                  0.00   
...                     ...                       ...                   ...   
20326                  0.00                      0.00                  1.00   
20327                  1.00                      1.00                  0.00   
20328                  0.00                      0.00                  0.00   
20329                  0.00                  

In [23]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import cross_val_score

In [24]:
import numpy as np

In [25]:
X = df.drop('label', axis='columns')
y = df.label

In [26]:
from sklearn.compose import make_column_transformer

In [27]:
column_trans = make_column_transformer(
    (OneHotEncoder(), ['protocol_type','service','flag']),
    remainder='passthrough')
logreg = LogisticRegression(solver='lbfgs')

In [28]:
column_trans.fit_transform(X)

array([[0.  , 1.  , 0.  , ..., 0.  , 0.05, 0.  ],
       [0.  , 0.  , 1.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , ..., 1.  , 0.  , 0.  ],
       ...,
       [0.  , 1.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , ..., 0.  , 1.  , 1.  ],
       [0.  , 1.  , 0.  , ..., 0.  , 0.  , 0.  ]])

In [29]:
pipe = make_pipeline(column_trans, logreg)

In [30]:
cross_val_score(pipe, X, y, cv=5, scoring='accuracy').mean()

C:\Users\vishal\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
C:\Users\vishal\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\vishal\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the

0.9017645130203775

In [31]:
pipe.fit(X,y)

C:\Users\vishal\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


Pipeline(memory=None,
         steps=[('columntransformer',
                 ColumnTransformer(n_jobs=None, remainder='passthrough',
                                   sparse_threshold=0.3,
                                   transformer_weights=None,
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories='auto',
                                                                drop=None,
                                                                dtype=<class 'numpy.float64'>,
                                                                handle_unknown='error',
                                                                sparse=True),
                                                  ['protocol_type', 'service',
                                                   'flag'])],
                                   verbose=False)),
                ('logisticregression',
                 LogisticRegres

In [107]:
df1=pd.read_csv("test.csv")

In [112]:
df1['label'] = df1['label'].astype(int)

C:\Users\vishal\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [115]:
df1['label'] = df1['label'].astype(str)
df1

C:\Users\vishal\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


duration protocol_type   service flag  src_bytes  dst_bytes  land  \
2             2           tcp  ftp_data   SF      12983          0     0   
5             0           tcp      http   SF        267      14515     0   
6             0           tcp      smtp   SF       1022        387     0   
8             0           tcp      http   SF        327        467     0   
11            0           tcp      smtp   SF        616        330     0   
...         ...           ...       ...  ...        ...        ...   ...   
22526         0           tcp      http   SF        274       1623     0   
22528         0           tcp      http   SF        280       6087     0   
22532         0           tcp      smtp   SF        794        333     0   
22533         0           tcp      http   SF        317        938     0   
22535         0           udp  domain_u   SF         42         42     0   

       wrong_fragment  urgent  hot  ...  dst_host_srv_count  \
2                   0       0    0  ...                  86   
5                   0       0    0  ...                 255   
6                   0       0    0  ...                  28   
8                   0       0    0  ...                 255   
11                  0       0    0  ...                 129   
...               ...     ...  ...  ...                 ...   
22526               0       0    0  ...                 255   
22528               0       0    0  ...                 255   
22532               0       0    0  ...                 141   
22533               0       0    0  ...                 255   
22535               0       0    0  ...                 252   

       dst_host_same_srv_rate  dst_host_diff_srv_rate  \
2                        0.61                    0.04   
5                        1.00                    0.00   
6                        0.11                    0.72   
8                        1.00                    0.00   
11                       0.51                    0.03   
...                       ...                     ...   
22526                    1.00                    0.00   
22528                    1.00                    0.00   
22532                    0.72                    0.06   
22533                    1.00                    0.00   
22535                    0.99                    0.01   

       dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
2                             0.61                         0.02   
5                             0.01                         0.03   
6                             0.00                         0.00   
8                             0.01                         0.03   
11                            0.00                         0.00   
...                            ...                          ...   
22526                         0.01                         0.04   
22528                         0.20                         0.04   
22532                         0.01                         0.01   
22533                         0.01                         0.01   
22535                         0.00                         0.00   

       dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
2                      0.00                       0.0                  0.00   
5                      0.01                       0.0                  0.00   
6                      0.00                       0.0                  0.72   
8                      0.00                       0.0                  0.00   
11                     0.00                       0.0                  0.33   
...                     ...                       ...                   ...   
22526                  0.00                       0.0                  0.00   
22528                  0.00                       0.0                  0.00   
22532                  0.01                       0.0                  0.00   
22533                  0.01                       0.0    

In [116]:
df1=df1.dropna()

In [117]:
X1 = df1.drop('label', axis='columns')
y1 = df1.label

In [118]:
prediction=pipe.predict(X1)

In [119]:
y1

2        0
5        0
6        0
8        0
11       0
        ..
22526    0
22528    0
22532    0
22533    0
22535    0
Name: label, Length: 9709, dtype: object

In [121]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(prediction,y1)
print(cm)
acc_score=accuracy_score(prediction,y1)
print(acc_score)

[[7989    0]
 [1720    0]]
0.8228447831908539


In [43]:
from sklearn.svm import SVC

In [44]:
svm_clf=SVC(gamma="auto")

In [45]:
pipe1 = make_pipeline(column_trans, svm_clf)

In [46]:
cross_val_score(pipe1, X, y, cv=5, scoring='accuracy').mean()

C:\Users\vishal\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)


0.9756393094016864

In [47]:
pipe1.fit(X,y)

Pipeline(memory=None,
         steps=[('columntransformer',
                 ColumnTransformer(n_jobs=None, remainder='passthrough',
                                   sparse_threshold=0.3,
                                   transformer_weights=None,
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories='auto',
                                                                drop=None,
                                                                dtype=<class 'numpy.float64'>,
                                                                handle_unknown='error',
                                                                sparse=True),
                                                  ['protocol_type', 'service',
                                                   'flag'])],
                                   verbose=False)),
                ('svc',
                 SVC(C=1.0, break_ties=False, 

In [48]:
prediction1=pipe1.predict(X1)

In [49]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm1=confusion_matrix(prediction1,y1)
print(cm1)
acc_score1=accuracy_score(prediction1,y1)
print(acc_score1)

[[10851    11     0     0     0]
 [   18  7994     0     0     0]
 [    0     0     1     0     0]
 [    0     0     0     2     0]
 [    0     0     0     0     6]]
0.998464227082561


In [50]:
from sklearn.model_selection import cross_val_score
score=cross_val_score(pipe1,X,y,cv=10)

C:\Users\vishal\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  % (min_groups, self.n_splits)), UserWarning)


In [51]:
score

array([0.97723663, 0.97988354, 0.98147168, 0.98040254, 0.97563559,
       0.97934322, 0.97086864, 0.97881356, 0.97192797, 0.97881356])

In [52]:
score.mean() 

0.9774396932284144